export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as WhyMe } from './WhyMe'
export { default as Process } from './Process'
export { default as Testimonials } from './Testimonials'
export { default as FAQ } from './FAQ'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as CookieConsent } from './CookieConsent'
export { default as FloatingUI } from './FloatingUI'
export { ThemeProvider, useTheme } from './ThemeProvider'
export { AccessibilityProvider, useAccessibility } from './AccessibilityProvider'
export { default as ParallaxSection, AnimatedShapes, AnimatedGradient } from './ParallaxSection'
